---
version: 3

build_arg_defaults:
   ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'

dependencies:
   ansible_core:
      package_pip: ansible_core
   ansible_runner:
      package_pip: ansible-runner
   galaxy: requirements.yml
   python: requirements.txt
   system: bindep.txt

images:
   base_image:
      name: docker.io/library/rockylinux:9.3

additional_build_steps:
   prepend_base:
      - RUN echo This is a prepend base command!

   prepend_final: |
      RUN whoami
      RUN cat /etc/os-release
   append_final:
      - RUN echo This is a post-install command!
      - RUN ls -la /etc
